---

- hosts: all 
  become: true
  tasks:

  - name: install apache2 and libapache2 packages
    package: 
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

